// ─────────────────────────────────────────────────────────────────────────────
// /api/_lib/concepts.js
// US Common Core-aligned concept banks per (subject, grade).
//
// WHY THIS EXISTS:
//   The pool was filling with near-duplicate quests because every batch request
//   used an identical prompt that said "pick ONE focused concept." Asked the same
//   question 30 times, Claude picked the single most canonical concept almost
//   every time (e.g. "Multiplying Fractions" for grade 5, "Systems of Linear
//   Equations" for grade 8). Result: 30 rows of the same quest.
//
//   The fix: assign each request a specific concept from the list below,
//   cycling through the list so the pool spreads evenly across the curriculum.
//
// USAGE:
//   import { conceptFor, conceptCount } from './concepts.js';
//   const concept = conceptFor('math', 8, i); // i = request index
// ─────────────────────────────────────────────────────────────────────────────

export const CONCEPTS = {
  math: {
    3: [
      'Multiplication within 100 (equal groups & arrays)',
      'Division within 100 (sharing & grouping)',
      'Understanding fractions as parts of a whole',
      'Comparing fractions with the same numerator or denominator',
      'Rounding to the nearest 10 and 100',
      'Adding and subtracting within 1000',
      'Area of rectangles by tiling and multiplication',
      'Perimeter of polygons',
      'Telling time to the minute and elapsed time',
      'Interpreting picture graphs and bar graphs',
      'Properties of multiplication (commutative, associative, distributive)',
      'Two-step word problems with the four operations',
    ],
    4: [
      'Multi-digit multiplication (up to 4 digits by 1 digit)',
      'Long division with remainders',
      'Equivalent fractions',
      'Adding and subtracting fractions with like denominators',
      'Multiplying a fraction by a whole number',
      'Understanding decimal notation for fractions (tenths & hundredths)',
      'Factors, multiples, prime and composite numbers',
      'Comparing multi-digit numbers using place value',
      'Angle measurement and classifying angles',
      'Area and perimeter word problems',
      'Patterns and rules in number sequences',
      'Converting units of measurement within a system',
    ],
    5: [
      'Multiplying fractions by fractions',
      'Dividing unit fractions by whole numbers',
      'Adding and subtracting fractions with unlike denominators',
      'Multiplying multi-digit whole numbers (standard algorithm)',
      'Dividing with two-digit divisors',
      'Adding and subtracting decimals to the hundredths',
      'Multiplying and dividing decimals',
      'Understanding place value to thousandths',
      'Volume of rectangular prisms',
      'Coordinate plane: plotting points in the first quadrant',
      'Order of operations with parentheses',
      'Converting measurement units (metric & customary)',
      'Interpreting line plots with fractional data',
    ],
    6: [
      'Ratios and ratio reasoning',
      'Unit rates and rate problems',
      'Dividing fractions by fractions',
      'Understanding negative numbers and the number line',
      'Absolute value and ordering rational numbers',
      'Writing and evaluating algebraic expressions',
      'Solving one-variable equations and inequalities',
      'Independent and dependent variables',
      'Area of triangles and quadrilaterals',
      'Surface area using nets',
      'Statistical variability: mean, median, mode, range',
      'Percentages as rates per 100',
    ],
    7: [
      'Proportional relationships and constant of proportionality',
      'Operations with rational numbers (all four operations)',
      'Solving multi-step equations',
      'Solving and graphing inequalities',
      'Percent increase, decrease, and percent error',
      'Scale drawings and similar figures',
      'Area and circumference of circles',
      'Angle relationships (complementary, supplementary, vertical)',
      'Volume and surface area of prisms',
      'Probability of simple and compound events',
      'Drawing inferences from random samples',
      'Distributive property and combining like terms',
    ],
    8: [
      'Solving systems of linear equations',
      'Slope and rate of change',
      'Graphing linear functions',
      'Understanding functions and function notation',
      'Integer exponents and properties of exponents',
      'Scientific notation operations',
      'Square roots and cube roots',
      'The Pythagorean theorem and its applications',
      'Transformations: translations, reflections, rotations, dilations',
      'Congruence and similarity through transformations',
      'Volume of cylinders, cones, and spheres',
      'Linear equations with one, none, or infinitely many solutions',
      'Comparing properties of functions (linear vs nonlinear)',
      'Bivariate data and scatter plots',
    ],
    9: [
      'Solving linear equations and inequalities in one variable',
      'Systems of linear equations and inequalities',
      'Factoring quadratic expressions',
      'Solving quadratic equations by factoring',
      'Solving quadratics with the quadratic formula',
      'Properties of exponents and radical expressions',
      'Arithmetic and geometric sequences',
      'Interpreting and graphing linear functions',
      'Graphing quadratic functions and finding vertex/intercepts',
      'Exponential growth and decay functions',
      'Polynomial addition, subtraction, and multiplication',
      'Interpreting key features of functions from graphs',
    ],
  },

  english: {
    3: [
      'Identifying the main idea and key details',
      'Asking and answering questions about a text',
      'Determining the meaning of words using context',
      'Describing characters and their motivations',
      'Distinguishing literal from nonliteral language',
      'Comparing themes across stories',
      'Using prefixes and suffixes to determine word meaning',
      'Recounting fables and folktales and their lessons',
      'Identifying the author\'s point of view',
      'Sequencing events in a narrative',
    ],
    4: [
      'Determining theme from details in a text',
      'Summarizing a text accurately',
      'Describing characters, settings, and events in depth',
      'Explaining how reasons support an author\'s points',
      'Interpreting figurative language (similes & metaphors)',
      'Comparing first- and third-person points of view',
      'Using context clues to determine word meaning',
      'Understanding common idioms and adages',
      'Integrating information from two texts on a topic',
      'Identifying text structure (cause/effect, compare/contrast)',
    ],
    5: [
      'Quoting accurately when explaining a text',
      'Determining two or more main ideas and supporting details',
      'Comparing and contrasting characters or events',
      'Analyzing how chapters or scenes fit together',
      'Interpreting figurative language including metaphors and similes',
      'Understanding the meaning of common idioms and proverbs',
      'Identifying an author\'s point of view and how it shapes a text',
      'Using context and word roots to determine meaning',
      'Comparing texts in the same genre',
      'Explaining relationships between individuals or events using text evidence',
    ],
    6: [
      'Citing textual evidence to support analysis',
      'Determining theme and how it develops across a text',
      'Analyzing how a particular sentence or paragraph fits the structure',
      'Determining an author\'s point of view or purpose',
      'Tracing and evaluating an argument and its claims',
      'Distinguishing connotative from denotative meanings',
      'Analyzing how word choice affects meaning and tone',
      'Comparing a text to an audio or video version',
      'Determining word meaning using Greek and Latin roots',
      'Identifying figurative, connotative, and technical meanings',
    ],
    7: [
      'Citing several pieces of textual evidence',
      'Analyzing how setting, plot, and character interact',
      'Determining how an author develops point of view',
      'Analyzing the structure an author uses to organize a text',
      'Evaluating an argument and assessing whether evidence is sound',
      'Analyzing how an author distinguishes their position from others',
      'Determining meaning of figurative and connotative language',
      'Comparing a fictional portrayal to a historical account',
      'Analyzing the impact of rhymes and repetition in poetry',
      'Interpreting words and phrases including technical meanings',
    ],
    8: [
      'Citing strong textual evidence and analyzing what is left uncertain',
      'Determining theme and its relationship to characters and setting',
      'Analyzing how dialogue or incidents propel action',
      'Analyzing how differences in character viewpoints create suspense or humor',
      'Evaluating the soundness of reasoning and relevance of evidence',
      'Analyzing how an author responds to conflicting viewpoints',
      'Determining the meaning of figurative and connotative language',
      'Analyzing the structure of a specific paragraph and its role',
      'Comparing the structure of two or more texts',
      'Analyzing how word choices affect meaning and tone',
    ],
  },

  science: {
    3: [
      'Forces and motion: balanced and unbalanced forces',
      'Patterns in motion that allow prediction',
      'Life cycles of plants and animals',
      'Inherited traits and the environment\'s influence',
      'Adaptations and survival in habitats',
      'Weather patterns and seasonal climate',
      'States of matter and changes',
      'Magnets and magnetic forces',
      'Fossils as evidence of past environments',
      'Group behavior and survival in animals',
    ],
    4: [
      'Energy and how it transfers',
      'Energy in collisions and motion',
      'Waves: amplitude and wavelength',
      'How light reflects and lets us see',
      'Plant and animal structures for survival',
      'How animals sense and process information',
      'Earth\'s features and weathering/erosion',
      'Rock layers and patterns over time',
      'Natural hazards and reducing their impact',
      'Renewable and nonrenewable energy resources',
    ],
    5: [
      'Matter is made of particles too small to see',
      'Conservation of mass in physical changes',
      'Mixtures and identifying substances by properties',
      'Energy flow from the sun through food webs',
      'The role of plants in producing food (photosynthesis basics)',
      'Earth\'s major systems and their interactions',
      'The water cycle and distribution of water on Earth',
      'Gravity and objects falling toward Earth',
      'Patterns of stars and the sun in the sky',
      'Protecting Earth\'s resources and environment',
    ],
    6: [
      'Cells as the basic unit of life',
      'Body systems and how they work together',
      'Photosynthesis and cellular respiration',
      'Weather, climate, and atmospheric circulation',
      'The water cycle and energy from the sun',
      'Thermal energy and heat transfer',
      'Kinetic and potential energy',
      'Earth\'s structure and plate tectonics',
      'Rock cycle and mineral formation',
      'Ecosystems: matter and energy flow',
    ],
    7: [
      'Chemical reactions and conservation of matter',
      'Atoms, molecules, and the structure of matter',
      'Forces, motion, and Newton\'s laws',
      'Genetics and inheritance of traits',
      'Natural selection and adaptation',
      'Populations and resource availability in ecosystems',
      'Cycling of matter in ecosystems',
      'Human impact on the environment',
      'Energy transfer in physical systems',
      'Cell structure and function',
    ],
    8: [
      'Newton\'s laws and forces between objects',
      'The structure of atoms and the periodic table',
      'Chemical reactions and properties of substances',
      'Waves: properties and information transfer',
      'The electromagnetic spectrum and light',
      'Gravity and the solar system',
      'Plate tectonics and Earth\'s history',
      'Natural selection and evidence of evolution',
      'Photosynthesis and cellular respiration in detail',
      'Energy conservation and transfer in systems',
    ],
  },

  history: {
    3: [
      'Communities and how they change over time',
      'Local government and community leaders',
      'Maps, globes, and geographic tools',
      'Native American cultures and regions',
      'Goods, services, and how communities trade',
      'Important national symbols and landmarks',
      'Holidays and their historical origins',
      'Rights and responsibilities of citizens',
      'How people adapt to their environment',
      'Cultural traditions around the world',
    ],
    4: [
      'Early exploration of the Americas',
      'Native American nations before European contact',
      'Geography of the United States: regions and features',
      'State history and government basics',
      'Colonization and early settlements',
      'Westward expansion and migration',
      'Branches of government and their roles',
      'Natural resources and economic regions',
      'Reading and interpreting historical maps',
      'Cause and effect in historical events',
    ],
    5: [
      'Early Americas and indigenous civilizations',
      'European exploration and its consequences',
      'The thirteen colonies and colonial life',
      'Causes of the American Revolution',
      'The Declaration of Independence',
      'The U.S. Constitution and Bill of Rights',
      'Branches and powers of the federal government',
      'Westward expansion and Manifest Destiny',
      'Geography\'s role in settlement and economy',
      'Interpreting primary source documents',
    ],
    6: [
      'Early human societies and the Neolithic Revolution',
      'Ancient Mesopotamia and the first civilizations',
      'Ancient Egypt and the Nile River civilization',
      'Ancient Greece: democracy and culture',
      'The Roman Republic and Empire',
      'Ancient India and the Indus Valley',
      'Ancient China and its dynasties',
      'World religions and belief systems in the ancient world',
      'Trade routes and cultural exchange',
      'Geography\'s influence on ancient civilizations',
    ],
    7: [
      'The fall of Rome and the early Middle Ages',
      'The Byzantine Empire',
      'The rise and spread of Islam',
      'Medieval Europe and feudalism',
      'African kingdoms: Ghana, Mali, and Songhai',
      'Imperial China and its innovations',
      'Feudal Japan and the samurai',
      'The Renaissance and humanism',
      'The Reformation and its consequences',
      'The Age of Exploration and global contact',
    ],
    8: [
      'Causes and events of the American Revolution',
      'The Constitution and the founding of the government',
      'The Bill of Rights and individual liberties',
      'Early presidents and the new nation\'s challenges',
      'Westward expansion and Manifest Destiny',
      'The Industrial Revolution in America',
      'Slavery, abolition, and sectional conflict',
      'Causes of the Civil War',
      'The Civil War and its major turning points',
      'Reconstruction and its aftermath',
    ],
  },
};

// Return the concept for a given (subject, grade) at request index i.
// Cycles through the list so the pool spreads evenly. If the list runs out,
// it wraps around — duplicates only begin once every concept is used once.
export function conceptFor(subjectId, gradeLevel, index) {
  const list = (CONCEPTS[subjectId] && CONCEPTS[subjectId][gradeLevel]) || null;
  if (!list || list.length === 0) return null;
  return list[index % list.length];
}

// How many distinct concepts exist for a combo (0 if none defined).
export function conceptCount(subjectId, gradeLevel) {
  const list = (CONCEPTS[subjectId] && CONCEPTS[subjectId][gradeLevel]) || null;
  return list ? list.length : 0;
}
